### ISSUE TITLE
compilation fails on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by schaumannj** [WAGO/tp-firmware-sdk#1]
Hi,
did you try to compile on Ubuntu 18? I did but I had the following errors

make[1]: Entering directory '/home/laborka/wago/ptxproj/platform-vtp-ctp/build-host/cpputest-3.1'
compiling PluginTest.cpp
compiling UtestTest.cpp
compiling TestResultTest.cpp
compiling MemoryLeakDetectorTest.cpp
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:56:63: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size, const char* file, int line) throw (std::bad_alloc);
                                                               ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:57:65: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size, const char* file, int line) throw (std::bad_alloc);
                                                                 ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size) throw(std::bad_alloc);
                                   ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size) throw(std::bad_alloc);
                                     ^~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:56:63: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size, const char* file, int line) throw (std::bad_alloc);
                                                               ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:57:65: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size, const char* file, int line) throw (std::bad_alloc);
                                                                 ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size) throw(std::bad_alloc);
                                   ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size) throw(std::bad_alloc);
                                     ^~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/UtestTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:56:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new(size_t size) throw(std::bad_alloc);
                                 ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:56:7: error: declaration of 'void* operator new(size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new(size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:9: note: from previous declaration 'void* operator new(size_t)'
   void* operator new(size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/UtestTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:57:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new[](size_t size) throw(std::bad_alloc);
                                   ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:57:7: error: declaration of 'void* operator new [](size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new[](size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:9: note: from previous declaration 'void* operator new [](size_t)'
   void* operator new[](size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/MemoryLeakDetectorTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:56:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new(size_t size) throw(std::bad_alloc);
                                 ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:56:7: error: declaration of 'void* operator new(size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new(size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:9: note: from previous declaration 'void* operator new(size_t)'
   void* operator new(size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/MemoryLeakDetectorTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:57:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new[](size_t size) throw(std::bad_alloc);
                                   ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:57:7: error: declaration of 'void* operator new [](size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new[](size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:9: note: from previous declaration 'void* operator new [](size_t)'
   void* operator new[](size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:56:63: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size, const char* file, int line) throw (std::bad_alloc);
                                                               ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:57:65: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size, const char* file, int line) throw (std::bad_alloc);
                                                                 ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size) throw(std::bad_alloc);
                                   ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size) throw(std::bad_alloc);
                                     ^~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:56:63: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size, const char* file, int line) throw (std::bad_alloc);
                                                               ^~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/PluginTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:56:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new(size_t size) throw(std::bad_alloc);
                                 ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:57:65: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size, const char* file, int line) throw (std::bad_alloc);
                                                                 ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new(size_t size) throw(std::bad_alloc);
                                   ^~~~~
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void* operator new[](size_t size) throw(std::bad_alloc);
                                     ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:56:7: error: declaration of 'void* operator new(size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new(size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:9: note: from previous declaration 'void* operator new(size_t)'
   void* operator new(size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/PluginTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:57:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new[](size_t size) throw(std::bad_alloc);
                                   ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:57:7: error: declaration of 'void* operator new [](size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new[](size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:9: note: from previous declaration 'void* operator new [](size_t)'
   void* operator new[](size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/TestResultTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:56:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new(size_t size) throw(std::bad_alloc);
                                 ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:56:7: error: declaration of 'void* operator new(size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new(size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:58:9: note: from previous declaration 'void* operator new(size_t)'
   void* operator new(size_t size) throw(std::bad_alloc);
         ^~~~~~~~
In file included from include/CppUTest/TestHarness.h:77:0,
                 from tests/TestResultTest.cpp:28:
include/CppUTest/MemoryLeakWarningPlugin.h:57:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void* operator new[](size_t size) throw(std::bad_alloc);
                                   ^~~~~
include/CppUTest/MemoryLeakWarningPlugin.h:57:7: error: declaration of 'void* operator new [](size_t) throw (std::bad_alloc)' has a different exception specifier
 void* operator new[](size_t size) throw(std::bad_alloc);
       ^~~~~~~~
In file included from <command-line>:0:0:
././include/CppUTest/MemoryLeakDetectorNewMacros.h:59:9: note: from previous declaration 'void* operator new [](size_t)'
   void* operator new[](size_t size) throw(std::bad_alloc);
         ^~~~~~~~
make[1]: *** [objs/tests/TestResultTest.o] Error 1
build/MakefileWorker.mk:404: recipe for target 'objs/tests/TestResultTest.o' failed
make[1]: *** Waiting for unfinished jobs....
build/MakefileWorker.mk:404: recipe for target 'objs/tests/PluginTest.o' failed
make[1]: *** [objs/tests/PluginTest.o] Error 1
build/MakefileWorker.mk:404: recipe for target 'objs/tests/MemoryLeakDetectorTest.o' failed
make[1]: *** [objs/tests/MemoryLeakDetectorTest.o] Error 1
build/MakefileWorker.mk:404: recipe for target 'objs/tests/UtestTest.o' failed
make[1]: Leaving directory '/home/laborka/wago/ptxproj/platform-vtp-ctp/build-host/cpputest-3.1'
make[1]: *** [objs/tests/UtestTest.o] Error 1
/home/laborka/wago/ptxproj/rules/host-cpputest.make:64: recipe for target '/home/laborka/wago/ptxproj/platform-vtp-ctp/state/host-cpputest.compile' failed
make: *** [/home/laborka/wago/ptxproj/platform-vtp-ctp/state/host-cpputest.compile] Error 2

**Comment by Thomas-Brandt** [comment]
Hello,
as written in the README.md you must use Ubuntu 16.04.5 (64bit) LTS.
Due to dependencies needed for compilation.
