### ISSUE TITLE
Document Minimum Memory Required for Build Host

### ISSUE THREAD

**Issue by c-born** [WAGO/tp-firmware-sdk#2]
Firstly, congratulations on the excellent documentation provided here on getting a build system up and running!

I've just bought a TP-600 for evaluation, knowing almost nothing about it, and wanting to get a "Hello World" program running, so following along with the instructions.

I set up a VM using the ISO and VMWare Workstation's Easy Install with default settings, except for setting the HD from 20GB to 50GB as recommended, however even after the "**Now it's probably time to go home for the day**"stage the build was still running the next day, and eventually crashed out.

Running `ptxdist go`  without the `q` option and with `j1` to constrain it to a single build at a time I found the compile where it was getting stuck, the problem looked like it was low on memory.

I then reconfigured the VM from the default 1GB memory and 1 CPU to 2GB memory (and 2 CPUs), ran `ptxdist go` again, and the problem compile was solved. (There was a later problem which I'll address in another Issue)

So from this, I suggest adding to the instructions a recommended minimum RAM of 2GB on a VM build host, it could save someone like me many hours trying to figure out what was going on!

**Comment by Thomas-Brandt** [comment]
Hi c-born! Thanks for the flowers! 
You'll know more RAM is always better! ;)
But I'll will give a hint in the docu.
