### ISSUE TITLE
Update Documentation on Build Host Location

### ISSUE THREAD

**Issue by c-born** [WAGO/tp-firmware-sdk#3]
The documentation says to get the build host from http://releases.ubuntu.com/16.04/
That link currently gets you Ubuntu 16.04.6 LTS 64bit rather than Ubuntu 16.04.5 LTS 64bit
As it is only a minor point release update I thought it would be ok, but no, apparently there was a change in the C++11 ABI that breaks the build of QtLocation, amongst other things. Now I know, you **MUST** use the exact release!

The required version can now be found here: http://old-releases.ubuntu.com/releases/16.04.5/
I used http://old-releases.ubuntu.com/releases/16.04.5/ubuntu-16.04.5-server-amd64.iso, which worked for me.

In section 3.1 I had to install three additional packages to those already listed:
```
make
gettext
bc
```

@Thomas-Brandt Do you want me to add these changes in a PR?

**Comment by Thomas-Brandt** [comment]
Done
