### ISSUE TITLE
ptxdist path

### ISSUE THREAD

**Issue by tkubt** [WAGO/tp-firmware-sdk#4]
Thank you for the Firmware SDK and Documentation. I use ubuntu-16.04.5-desktop-amd64.iso in a VirtualBox VM with no further updates. However i have problems with the ptxdist config and kernel-header checksum.

4.1) Select "software config" we want to build

Documentation says:
```
    >cd ~/wago/ptxproj
    >ptxdist select configs/vtp-ctp/ptxconfig_generic
    info: selected ptxconfig:
          'configs/vtp-ctp/ptxconfig_generic'
```
Output is:
```
    >cd ~/wago/ptxproj
    >ptxdist select configs/vtp-ctp/ptxconfig_generic
    error: cannot select
	'configs/vtp-ctp/ptxconfig_generic'
	does not exist, or is not a file
```
This path works:
```
    >cd ~/wago/ptxproj
    >ptxdist select tp-firmware-sdk/configs/vtp-ctp/ptxconfig_generic
    info: selected ptxconfig:
	'tp-firmware-sdk/configs/vtp-ctp/ptxconfig_generic'
```
Same goes for 4.2) Select "hardware platform" to dial with

But at the step 5.1)
`ptxdist go -q`
the output is:
```
started: linux-4.9.146.tar.xz
started: kernel-header.get
ptxdist: error: Wrong md5sum for 'kernel-header' (/home/tk/wago/ptxproj/src/linux-4.9.146.tar.xz)
make: *** [home/tk/wago/ptxproj/platform-vtp-ctp/state/kernel-header.get] Error 1
```

**Comment by Helmut-Saal** [comment]
Please install LFS Support, see manual.
BG Helmut

**Comment by tkubt** [comment]
I followed the manual, git-lfs is installed.
EDIT: Sorry, my fault, I missed the '.' in
`git clone https://github.com/WAGO/tp-firmware-sdk.git .`
