### ISSUE TITLE
HowTo access TP600/Edge controller I/Os

### ISSUE THREAD

**Issue by quenorha** [WAGO/tp-firmware-sdk#9]
Could we get a HowTo to access digital I/O of TP600 or Edge Controller (PIO3), like we have for CC100 ? Thanks

**Comment by c-born** [comment]
Seconded!
In April 2022 I emailed Thomas Brandt asking for an example of using the DIO on the TP600, and followed it up three months with the same request from our local supplier after we bought 23 x TP600s from them, but have heard nothing back to date.
The final one was commissioned two days ago and they are performing really well in a very rugged environment.

**Comment by falk-werner** [comment]
Unfortunately, there is no HowTo available at the moment. But I can provide a brief description:

### Output

- set bit 1:  
`echo 1 > /sys/bus/spi/devices/spi3.1/dio`
- set all bits:  
`echo 15 > /sys/bus/spi/devices/spi3.1/dio`
- reset all bits:
`echo 0 > /sys/bus/spi/devices/spi3.1/dio`

### Input

`cat /sys/bus/spi/devices/spi3.1/dio`

- a value of 7952 means 0
- a value of 7953 means bit 1 is set

**Comment by c-born** [comment]
Nice, thanks so much for that!
I spent way too long trying to work out how to use the driver, which only looks to be partially complete.

With this info I can do:

``while true; do  echo "obase=2; `cat /sys/bus/spi/devices/spi3.1/dio`" | bc ; sleep 1; done``

and watch the bit flip as I toggle my switch, from here on should be straight forward.
```
1000111100010001
1000111100010000
1000111100010001
```
